# Default values for Gradle projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: 100.66.15.130:5000/ci-makingdevs/emailer-app
  tag: 0.0.49
  pullPolicy: IfNotPresent
service:
  name: emailer-app
  type: ClusterIP
  externalPort: 80
  internalPort: 8000
  annotations:
    fabric8.io/expose: "true"
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 400m
    memory: 512Mi
probePath: /actuator/health
livenessProbe:
  httpGet:
    path: /healthz
    port: 8000
    scheme: HTTP
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  httpGet:
    path: /healthz
    port: 8000
    scheme: HTTP
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
terminationGracePeriodSeconds: 10
